### ISSUE TITLE
Names in WebID profile diagram

### ISSUE THREAD

**Issue by theRealImy** [solid/webid-profile#3]
In our texts we mostly make use of `Preference File` and the predicate is also with preferenceFile. [The diagram](https://github.com/solid/webid-profile/blob/main/notes/discovery2.png) contains `Preference Document`. This might be confusing.
Same for `Type index File`(Document).

**Comment by jeff-zucker** [comment]
In the meeting we decided we should call them all documents and have a note in the section on the pim:preferencesFile predicate that we call it a document rather than file for consistency with the OIDC spec which uses "WebID Profile Document".

By the way, the predicate is plural "pim:preferencesFile" not "pim':preferenceFile".
