### ISSUE TITLE
Extended Profile `rdfs:seeAlso` vs `foaf:isPrimaryTopicOf` discrepancy

### ISSUE THREAD

**Issue by m14t** [solid/webid-profile#45]
I believe I may have come across some conflicting information on how to properly discover a user's full extended profile.

The current [website](https://solid.github.io/webid-profile/#reading-extended-profile-documents) [[source](https://github.com/solid/webid-profile/blob/31241b74f5f590895dc9f7d693e485e998688dbc/index.html#L1314)] mentions that you can follow a `rdfs:seeAlso` predicate on the WebID Profile Document to reach the extended profile.

However on a WebID Profile Document from WebID created today on https://start.inrupt.com/, once a pod is created, the profile document is referred to via the `foaf:isPrimaryTopicOf` predicate. Example: https://id.inrupt.com/inruptmatt

This new behavior seems to be correct according to PR #2.

Possibly related discussions: #40 

If this is correct, would it be possible to update the website with this new information?

**Comment by jeff-zucker** [comment]
The whole point of issue #40 is to see if it's possible to align the spec with the kind of server setup that uses foaf:priamraryTopicOf.  So until that issue is settled some servers will remain out of sync with the spec you pointed to.  Since this spec was very recently published and is in flux, there is no reason to expect servers to follow it yet.  Hopefully we will soon come up with a solution that works for all.

**Comment by jeff-zucker** [comment]
Closing ,as it is entirely depend on #40.  Please direct further discussion there.
